version: '3'

services:
  #  postgres:
  #    image: postgres:latest
  #    container_name: my-postgres-db
  #    ports:
  #      - "5432:5432"
  #    environment:
  #      POSTGRES_DB: my_courier_db
  #      POSTGRES_USER: my_courier_user
  #      POSTGRES_PASSWORD: my_courier_password

  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: 'licenta_db'
      MYSQL_USER: 'courier'
      MYSQL_PASSWORD: 'courier'
      MYSQL_ROOT_PASSWORD: 'courier'
    ports:
      - "3333:3306"
    expose:
      - '3333'
    volumes:
      - mysql_data:/var/lib/mysql


#  my-courier-app:
#    build: ./CourierAPP
#    image: my-courier-app:latest
#    ports:
#      - "4000:8080"
#    restart: always
#    depends_on:
#      - mysql
#    environment:
#      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql:3306/licenta_db'
#      SPRING_DATASOURCE_USERNAME: 'courier'
#      SPRING_DATASOURCE_PASSWORD: 'courier'
#  #    networks:
#  #      - backend
#  #
#  my-courier-app-auth:
#    build: ./CourierAPPAuth
#    image: my-courier-app-auth:latest
#    ports:
#      - "5000:8080"
#    restart: always
#    depends_on:
#      - mysql
#    environment:
#      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql:3306/licenta_db'
#      SPRING_DATASOURCE_USERNAME: 'courier'
#      SPRING_DATASOURCE_PASSWORD: 'courier'
#
#  portainer:
#    image: portainer/portainer-ce:latest
#    container_name: portainer_container
#    restart: always
#    ports:
#      - "9000:9000"
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - portainer_data:/data
volumes:
  mysql_data:
#  portainer_data: